name: Cinny Client Staging

on:
    push:
        branches:
            - staging

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    VITE_USERNAME: ${{ secrets.VITE_USERNAME }}
    VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}
    VITE_SUPPORT_ROOM_ID: ${{ secrets.VITE_SUPPORT_ROOM_ID }}
    
jobs:
    Deploy-Staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2

            - name: Install Node
              id: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.12.1

            - name: Install Dependencies
              id: install-deps
              run: npm install

            - name: Set up config.json
              id: setup-config
              run: |
                echo '{
                "defaultHomeserver": 0,
                "homeserverList": ["staging-matrix.momentify.xyz"],
                "allowCustomHomeservers": true
                }' > config.json

            - name: Build
              id: build
              run: npm run build

            - name: Deploy Staging
              id: deploy
              run: npm run aws:deploy:staging

            - name: Post to Slack Success
              id: slack_success
              if: ${{ steps.deploy.outcome == 'success' }}
              uses: slackapi/slack-github-action@v1.24.0
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                          "blocks": [
                              {
                                  "type": "header",
                                  "text": {
                                      "type": "plain_text",
                                      "text": ":gear: Staging Deploy Success",
                                      "emoji": true
                                  }
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": " :memo: *Summary:*"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "Triggered by: ${{ github.actor }}\nrun link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                  }
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": ":book: forked-cinny-client"
                                  }
                              }
                          ]
                      }

            - name: Post to Slack Fail
              id: slack_fail
              if: ${{ steps.deploy.outcome != 'success'}}
              uses: slackapi/slack-github-action@v1.24.0
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                          "blocks": [
                              {
                                  "type": "header",
                                  "text": {
                                      "type": "plain_text",
                                      "text": ":rotating_light: Staging Deploy Failed",
                                      "emoji": true
                                  }
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": " :memo: *Summary:*"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "Triggered by: ${{ github.actor }}\nVisit the run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                  }
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": ":book: forke-cinny-client"
                                  }
                              }
                          ]
                      }
